name: fl_wx
description: Simple encapsulation and extension of fluwx,The fluwx plugin will be updated here.
version: 0.0.3
repository: https://github.com/Wayaer/fl_wx.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluwx: ^4.3.2

dev_dependencies:
  flutter_lints: ^3.0.0


