name: fl_wx
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/Wayaer/fl_wx.git

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluwx: ^4.2.7

dev_dependencies:
  flutter_lints: ^2.0.2


